### ISSUE TITLE
Receiving a Thrift::ApplicationException: "Invalid method name:  'executeAndWait'"

### ISSUE THREAD

**Issue by NeMO84** [colinmarc/impala-ruby#19]
Code
-------
* Ruby 2.1.0
* Impala - 0.4.3
* Thrift - 0.9.2.0

```ruby
host = "localhost"
port = 21000
db = "impala_db"
impala = Impala.connect(host, port)
impala.execute("use #{db}") # <--- Causes the exception!
```

Stacktrace
-------------
/Users/nemo/.rvm/gems/ruby-2.1.0@project/gems/thrift-0.9.2.0/lib/thrift/client.rb:67:in `handle_exception'
/Users/nemo/.rvm/gems/ruby-2.1.0@project/gems/thrift-0.9.2.0/lib/thrift/client.rb:55:in `receive_message'
/Users/nemo/.rvm/gems/ruby-2.1.0@project/gems/impala 0.4.3/lib/impala/protocol/beeswax_service.rb:43:in `recv_executeAndWait'
/Users/nemo/.rvm/gems/ruby-2.1.0@project/gems/impala 0.4.3/lib/impala/protocol/beeswax_service.rb:35:in `executeAndWait'
/Users/nemo/.rvm/gems/ruby-2.1.0@project/gems/impala-0.4.3/lib/impala/connection.rb:99:in `send_query'
/Users/nemo/.rvm/gems/ruby-2.1.0@project/gems/impala-0.4.3/lib/impala/connection.rb:74:in `execute'

Notes
--------
* It did work a while back, but I haven't used the code for a couple months and I came back to implement the remaining items and it didn't work. I am already on the latest version of Impala. 
* I haven't tried being on the bleeding edge version yet.
* I am port forwarding to a remote server hosting ImpalaDB. I confirmed the configuration is correct as when I change the configuration to an incorrect value it will error out with the expected can't connect message.

Any help is appreciated!

**Comment by ljank** [comment]
@NeMO84 are you sure you're connecting to the right port? There are 2 Impala Frontend ports that are easy to mix:

- 21000: Used to transmit commands and receive results by impala-shell, Beeswax, and version 1.2 of the Cloudera ODBC driver.
- 21050: Used to transmit commands and receive results by applications, such as Business Intelligence tools, using JDBC and version 2.0 or higher of the Cloudera ODBC driver.

The former one should be used to connect with thrift. Learned that the hard way :(

**Comment by NeMO84** [comment]
Actually, I don't remember what I ended up doing. But I did get past the issue. Sorry, wish I could confirm or deny your question/suggestion.

Closing issue, thanks!
